// <auto-generated />
using KingPriceAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KingPriceAssessment.Data.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250531170106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KingPriceAssessment.Data.Tables.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Facility"
                        });
                });

            modelBuilder.Entity("KingPriceAssessment.Data.Tables.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("KingPriceAssessment.Data.Tables.EmployeeAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeAllocation");
                });

            modelBuilder.Entity("KingPriceAssessment.Data.Tables.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Excecutive"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "Supervisour"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "Standard"
                        });
                });

            modelBuilder.Entity("KingPriceAssessment.Data.Tables.EmployeeAllocation", b =>
                {
                    b.HasOne("KingPriceAssessment.Data.Tables.Department", "Department")
                        .WithMany("EmployeeAllocation")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingPriceAssessment.Data.Tables.Employee", "Employee")
                        .WithMany("EmployeeAllocation")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KingPriceAssessment.Data.Tables.Role", "Role")
                        .WithMany("EmployeeAllocation")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KingPriceAssessment.Data.Tables.Department", b =>
                {
                    b.Navigation("EmployeeAllocation");
                });

            modelBuilder.Entity("KingPriceAssessment.Data.Tables.Employee", b =>
                {
                    b.Navigation("EmployeeAllocation");
                });

            modelBuilder.Entity("KingPriceAssessment.Data.Tables.Role", b =>
                {
                    b.Navigation("EmployeeAllocation");
                });
#pragma warning restore 612, 618
        }
    }
}
